# Generated by Django 4.2.2 on 2023-06-13 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_transaction_price_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='date',
        ),
    ]
