# Generated by Django 4.2.2 on 2023-06-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tax_b3',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
